# Generated by Django 4.1.3 on 2023-05-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_order_menuitem_created_at_menuitem_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
