# Generated by Django 4.1.3 on 2023-05-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_cartitem_total_price_cartitem_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
