# Generated by Django 4.1.3 on 2023-05-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_rename_review_restaurantreview_menureview'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
