# Generated by Django 4.1.3 on 2023-05-14 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_menuitem_avg_rating_menuitem_num_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant'),
        ),
    ]
